theme: jekyll-theme-minimal
title: Carotid Vessel Wall Segmentation Challenge
description: Carotid Vessel Wall Segmentation and Atherosclerotic Lesion Diagnosis Challenge
show_downloads: False
navigation:
  - title: Home
    url: index
  - title: Dataset Info
    url: 
  - title: Timeline
    url: 
  - title: Submission
    url: 
  - title: Organizers
    url: 
  - title: Leaderboard
    url: 
